### PR TITLE
Hero Bottom Component

### PR DESCRIPTION
**Pull request by oscarwang20**
### Summary 

This PR adds a responsive bottom component containing information about DTI's courses, outreach, and team.

### Notion/Figma Link 

https://www.notion.so/Home-Page-Course-Outreach-Team-Component-dd5d6415d8734467adca72b6042773e0?pvs=4

### Test Plan 

Here is the code for `page.tsx` and what gets rendered:
```
import { Button } from '../../components/ui/button';
import Navbar from '../../components/navbar';
import Bottom from '../../components/bottom';

const Home = (): JSX.Element => (
  <div>
    <Navbar />
    <Button>This is a ShadCN Button.</Button>
    <Bottom />
  </div>
);

export default Home;
```

Courses 
(desktop)
image
(tablet)
image
(mobile)
image

Outreach 
(desktop)
image
(tablet)
image
(mobile)
image

Team 
(desktop)
image
(tablet)
image
(mobile)
image

### Notes 

- Currently missing the line components connecting the images and other parts of the component
image

### CODE REVIEW

**Comment by andrew032011** [comment]
I can't see this in the deploy preview. Is it hidden? Can I see how it fits in with the rest of the page?

**Comment by oscarwang20** [comment]
> Screenshots look really cool! I can't see this in the deploy preview. Is it hidden? I'd like to see how it fits in with the rest of the page.

It should be visible now, can you check again?

**Comment by andrew032011** [comment]
This looks really nice! Love the responsiveness. 

Noticed some layout issues:

I think right now the footer has the "fixed" property set. If we deselect that, it should be on the bottom. The Nav bar looks like it's buried underneath the bottom component now.

**Comment by oscarwang20** [comment]
The hamburger menu toggle should be fixed now too.

**Pull request merged**
