### PR TITLE
Add Ability to Edit Candidate Decider Instance

### PR DESCRIPTION
**Pull request by andrew032011**
### Summary 

- Add ability to edit `authorizedMembers`, `authorizedRoles`, and `name` for candidate decider instances. Also change the `toggleCandidateDeciderInstance` endpoint to be `updateCandidateDeciderInstance`.
- Fix some typos in error messages

### Notion/Figma Link 

[](https://www.notion.so/cornelldti/Candidate-Decider-Add-Ability-to-Edit-Candidate-Decider-Instance-51432c0833f942229e42b588f15e4999?pvs=4)

### Test Plan 

Demo video:
https://github.com/cornell-dti/idol/assets/59291082/4a026774-75b0-4521-8db9-83754ebb78cc

### CODE REVIEW

**Review by oscarwang20 — COMMENTED** [review]
I think we should remove `lead` from the role selection menu just for clarity because the modal already has a section that says leads automatically have access.

**Comment by oscarwang20** [comment]
Small issue: adding more members/ roles shifts the modal header up:
image
Maybe we can make the content inside the modal scrollable?

**Comment by andrew032011** [comment]
> I think we should remove lead from the role selection menu just for clarity because the modal already has a section that says leads automatically have access.

Agreed, removed. I made the component more customizable so it's reusable in the future.

**Comment by andrew032011** [comment]
> Small issue: adding more members/ roles shifts the modal header up: image Maybe we can make the content inside the modal scrollable?

Done. Limited height of modal to 60% of viewport height and made it scrollable.

**Review by oscarwang20 — APPROVED** [review]
Looks great! This is another small thing I didn't catch earlier, but just something else to consider – all the users filtered through the search bar show up underneath it, taking up more space in the modal as more users are displayed.

I think we could make it more similar to the users display on the edit users page and have it just display 3-4 filtered users at a time, but it might not be necessary for now because scrolling down in the modal lets us get to all the users.

**Comment by andrew032011** [comment]
> Looks great! This is another small thing I didn't catch earlier, but just something else to consider – all the users filtered through the search bar show up underneath it, taking up more space in the modal as more users are displayed.
> 
> I think we could make it more similar to the users display on the edit users page and have it just display 3-4 filtered users at a time, but it might not be necessary for now because scrolling down in the modal lets us get to all the users.

Yeah, agreed that it's not as compact as it could be. You're suggesting I make the users part scrollable?

Maybe we could add a few more columns and use some of that horizontal space as well.

**Comment by andrew032011** [comment]
Merging this in for now to unblock more changes here. We can write up another ticket for UX improvements.

**Pull request merged**
