### PR TITLE
Allow members to add their pronouns and display on DTI website 

### PR DESCRIPTION
**Pull request by henry-li-06**
### Summary 
This PR allows members to update their pronouns on IDOL and displays them on the DTI website.

image

image

### Test Plan 
- IDOL ->Test on Netlify deploy preview 
- DTI website -> Test locally that is displays properly

### CODE REVIEW

**Review by JacksonStaniec — APPROVED** [review]
Should pronouns be right next to the name? Would it be more consistent stylistically if everyone was "_Name_ \n _Role_", but since pronouns are important, they should be the first field above "**graduating**"?

**Comment by henry-li-06** [comment]
> > Should pronouns be right next to the name? Would it be more consistent stylistically if everyone was "_Name_ \n _Role_", but since pronouns are important, they should be the first field above "**graduating**"?
> 
> 
> 
> I think it’s good that they are next to the name but maybe we can add a space between them, make them a lighter gray, and make them a bit smaller? Similar to how Instagram does it? Just to differentiate the name from the pronouns @henry-li-06 

@morganbelous Oh good idea (I want designer...), how exactly does Instagram do it?

**Comment by henry-li-06** [comment]
image
@morganbelous thoughts on this?

**Comment by morganbelous** [comment]
> image
> @morganbelous thoughts on this?

looks good to me!

**Pull request merged**
