### PR TITLE
added Jason,Hope,and Henry to readme

### PR DESCRIPTION
**Pull request by kembayeb**
### Summary 

added Hope and Jason to Spring 2023 contributors 
added Henry as Fall 2022 dev 

Notion
https://www.notion.so/cornelldti/Add-Jason-and-Hope-to-README-979c08806cda41ff885d5839e9da0bff

### CODE REVIEW

**Review by andrew032011 — APPROVED** [review]
If it's not too much trouble, while we're here, I think it would make sense to also

Add Clara Lee (Designer) to Fall 2022
And remove Daniel Jin from Fall 2022

I will add that to the ticket.

**Comment by kembayeb** [comment]
> If it's not too much trouble, while we're here, I think it would make sense to also
> 
> Add Clara Lee (Designer) to Fall 2022 And remove Daniel Jin from Fall 2022
> 
> I will add that to the ticket.

no problem!

**Comment by andrew032011** [comment]
And a very small thing, but I would try to keep consistency between using the words "Design" and "Designer" on the README.

**Comment by kembayeb** [comment]
> And a very small thing, but I would try to keep consistency between using the words "Design" and "Designer" on the README.

yea most def, i had changed tracy to designer to follow this

**Pull request merged**
