### PR TITLE
Setup dev Firebase instance 

### PR DESCRIPTION
**Pull request by henry-li-06**
### Summary 

I just set up another Firebase instance for development so that testing doesn't affect the data in the production Firebase instance. This way changes in our data due to testing will not affect the production data and potentially cause the DTI website to unnecessarily rebuild. 

### Test Plan 

N/A

### Notes 
- All of you should've received an invitation to the development Firebase instance
- The data in the development Firebase instance isn't complete

### CODE REVIEW

**Comment by SamChou19815** [comment]
@henry-li-06 can you document how you can run the server using prod vs dev dababase in some readme file? Also how does it affect deployed server in preview and prod?

**Comment by henry-li-06** [comment]
> @henry-li-06 can you document how you can run the server using prod vs dev dababase in some readme file? Also how does it affect deployed server in preview and prod?

I don't think it should have any effect on production. It should just change the Firebase instance that the backend/frontend uses by default when testing things locally. That way our production data doesn't get messed with and cause unnecessary redeploys.

**Comment by henry-li-06** [comment]
Seems to actually cause an issue w/ the preview server.... I'll take a look at that

**Review by SamChou19815 — APPROVED** [review]
Looks like the preview is now correctly using the dev db. Not sure what's happening in production, but if the production uses prod db then everything looks good to me.

**Comment by henry-li-06** [comment]
I'm still having an issue with logging into the IDOL preview so I'm gonna try to figure out what's going on there first.

**Comment by henry-li-06** [comment]
@SamChou19815 I think the issue w/ logging in should be fixed now. The preview should now be using the production database. Could you take another look just to make sure everything looks ok?

**Review by SamChou19815 — APPROVED** [review]
yes it seems to be working now

**Pull request merged**
