### PR TITLE
Added date to team events dropdown

### PR DESCRIPTION
**Pull request by kembayeb**
- Sorted dropdown events in reverse chronological order

changed the date object to be in a more representable format -example: Tuesday, Feb 14, 2023

### CODE REVIEW

**Comment by henry-li-06** [comment]
Great work! I think the date/time display might look nicer as `<event-name> (<time>)` or something like that to add a little more distinction between the event name and the time. Open to other suggestions tho

**Comment by henry-li-06** [comment]
Also please fill out the PR template in the future, it's there for a reason!

**Comment by kembayeb** [comment]
> Great work! I think the date/time display might look nicer as `<event-name> (<time>)` or something like that to add a little more distinction between the event name and the time. Open to other suggestions tho

**Comment by kembayeb** [comment]
> Great work! I think the date/time display might look nicer as `<event-name> (<time>)` or something like that to add a little more distinction between the event name and the time. Open to other suggestions tho

Most def, also tried bolding the event-name in this format, but it wasnt to appealing to look at. What you think?

**Comment by kembayeb** [comment]
> Also please fill out the PR template in the future, it's there for a reason!

got it!

**Comment by henry-li-06** [comment]
> > Great work! I think the date/time display might look nicer as `<event-name> (<time>)` or something like that to add a little more distinction between the event name and the time. Open to other suggestions tho
> 
> Most def, also tried bolding the event-name in this format, but it wasnt to appealing to look at. What you think?

Since we have work session later today, we can just quickly talk about the design with the rest of the team?

**Comment by andrew032011** [comment]
@kembayeb I'm aware you're making a few changes right now before this will be ready for review. When you're done with those and it's ready for review, I would either put a note here or post in #idol-dev that this is ready for another look.

**Comment by kembayeb** [comment]
added a date label, I think its ready for another look

**Comment by andrew032011** [comment]
In the future, it would be nice to attach screenshots for UI changes like this. This is what the design looks like:

Screen Shot 2023-03-08 at 12 42 15 AM

If the team already discussed this and decided on something else, feel free to ignore these:

Personally I would like to keep the info short and sweet, so
- I would set the weekday to be `'short'`
- I might not include the year. Especially neither a given Spring nor Fall semester will span more than 1 year
- I am tempted to take the weekday out altogether actually, since I don't know how important it is to remember the day of the week of a team event when filling out this form.

**Comment by kembayeb** [comment]
> In the future, it would be nice to attach screenshots for UI changes like this in the PR description. Makes it easier to look and critique the design.
> 
> This is what the design looks like:
> 
> Screen Shot 2023-03-08 at 12 42 15 AM
> 
> If the team already discussed this and decided on something else, feel free to ignore these:
> 
> Personally I would like to keep the info short and sweet, so
> 
> * I would set the weekday to be `'short'`
> * I might not include the year. Especially neither a given Spring nor Fall semester will span more than 1 year
> * I am tempted to take the weekday out altogether actually, since I don't know how important it is to remember the day of the week of a team event when filling out this form.

No problem! I like this idea of removing the weekday, make it look cleaner and more concise

**Comment by henry-li-06** [comment]
I think LGTM but will let the others take another look

**Comment by andrew032011** [comment]
> here is how it looks, currently
> Screen Shot 2023-03-08 at 10 32 55 AM

I like this!

**Review by andrew032011 — APPROVED** [review]

**Comment by andrew032011** [comment]
Overall this looks really great. Yes it would be nice to hear another opinion before merging this in.

**Comment by kembayeb** [comment]
> this change has not been pushed. I tried running ur branch, and I get your old design.
> Otherwise, LGTM.

 should be pushed now!

**Comment by mly32** [comment]
Some small changes that might be out of scope for this PR, but...

Once an event is selected, the view shows the # credit per hour. I feel like it wouldn't hurt for the dropdown to also show that info.

I also think it'd be nice for the clear button to be right justified and also have the team event info be a one-liner here:

image

**Comment by andrew032011** [comment]
> 

I would agree with the suggestion to put the hours in the dropdown. That behavior would align with what we currently see in the Google form. The dropdown is for submitting TEC but it's also a good spot to see upcoming different opportunities for TEC all in one place.

Agreed also that there could be improvements to the UI overall. Other frontend changes not related to the dropdown should go into another ticket. I can take care of writing that up.

Screen Shot 2023-03-09 at 9 46 25 AM

> Some small changes that might be out of scope for this PR, but...
> 
> Once an event is selected, the view shows the # credit per hour. I feel like it wouldn't hurt for the dropdown to also show that info.
> 
> I also think it'd be nice for the clear button to be right justified and also have the team event info be a one-liner here:
> 
> image

**Comment by andrew032011** [comment]
TEC styling ticket posted here: https://www.notion.so/cornelldti/Improve-TEC-Styling-3451c0d15a694db39143a6838a25908e?pvs=4

@kembayeb since you're finishing up here, I assigned this one to you to work on afterwards. I would save anything styling related for this ticket and focus exclusively on the dropdown UI here.

**Comment by kembayeb** [comment]
currently how the dropdown looks 

Screen Shot 2023-03-11 at 1 40 09 PM

**Comment by JacksonStaniec** [comment]
> currently how the dropdown looks
> 
> Screen Shot 2023-03-11 at 1 40 09 PM

I really like this look! If others are feeling it too, we make the Dev portfolio dropdown look like this too.

**Comment by andrew032011** [comment]
> > currently how the dropdown looks
> > Screen Shot 2023-03-11 at 1 40 09 PM
> 
> I really like this look! If others are feeling it too, we should make the Dev Portfolio dropdown look like this too.

+1 on this!

**Comment by oscarwang20** [comment]
> > > currently how the dropdown looks
> > > Screen Shot 2023-03-11 at 1 40 09 PM
> > 
> > 
> > I really like this look! If others are feeling it too, we should make the Dev Portfolio dropdown look like this too.
> 
> +1 on this!

Looks good to me too! I think it would look cleaner if we format the credits description to check for plurality, so instead of it saying `1 credit(s)` it says `1 credit`

**Comment by kembayeb** [comment]
> > > > currently how the dropdown looks
> > > > Screen Shot 2023-03-11 at 1 40 09 PM
> > > 
> > > 
> > > I really like this look! If others are feeling it too, we should make the Dev Portfolio dropdown look like this too.
> > 
> > 
> > +1 on this!
> 
> Looks good to me too! I think it would look cleaner if we format the credits description to check for plurality, so instead of it saying `1 credit(s)` it says `1 credit`

agreed

**Pull request merged**
