### PR TITLE
DTI48 GAME!

### PR DESCRIPTION
**Pull request by SamChou19815**
### Summary 

This PR implements the DTI48 game as proposed in the meeting.

You start as yourself. 2 of you create your manager, 2 of your manager create your manager's manager, etc, until you win by merging together two ops leads.

### Features

- Restart game
- Play as another DTI member

### Organization Tree

Using the following rules:

dev < TPM < @chansen424 < @JBoss925 < @meganyin13 < Ops Lead
design < PM < Product Lead < Ops Lead
business < Ehi < Ops Lead
Design Lead < Ops Lead

This isn't ideal, but we are constrained by the fact that one node can only have one parent, so at some point we make to make decisions like does design belong to PM or design leads. In the future, we can provide customization abilities.

Another issue is how which dev lead to be the parent of all TPMs. I don't have an answer, so I just make an order of dev leads based on netid alphabetical order.

### Test Plan 

dti48

### Notes 

Some of the data of the new members are not accurate. We need to fix that!

### CODE REVIEW

**Comment by henry-li-06** [comment]
image
image

I'm getting an issue where headshots for some members sometimes appear but then sometimes don't

**Comment by henry-li-06** [comment]
But otherwise looks good

**Comment by SamChou19815** [comment]
@henry-li-06 I just fixed that in the previous commit. Can you try again?

**Review by henry-li-06 — APPROVED** [review]
Oh ok looks good now

**Pull request merged**
