### PR TITLE
DTI Website, new "Hero" component

### PR DESCRIPTION
**Pull request by kevinmram**
[WIP] PR for Website Redesign: (https://www.notion.so/cornelldti/Idol-FA23-08f1aac52a364b1dad8cde77ebc1c027?p=3115c9e60d714b1eb3a17edfcd12c582&pm=s)

The Hero now features:

- an updated background
- user-interactive icons; (change in response to various user actions, including clicks and hover states, or remain static depending on user preference.)
- an advanced carousel of photographs; (interacts based on user's icon selection, presenting relevant visual content in a streamlined manner. Otherwise, equipped with an automation feature: in the event of user inactivity, the system initiates a timed progression of the photo sequence.)
- functionality where specific icons correlate with certain images has been instituted. This synchronized display fosters a coherent and interactive environment, enabling users to navigate and understand the platform's content.
- 
- [x] implemented features, functionality.
- [x] missing pictures and frames.

Screenshot 2023-10-20 162134

### CODE REVIEW

**Review by patriciaahuang — COMMENTED** [review]
Looks good so far! The only thing I'm seeing is that the purple image size is smaller than the rest of the images (red, blue, orange, and yellow), but that should be a quick fix.

**Review by alyssayzhang — COMMENTED** [review]
this looks good so far! for the icons, maybe we could use svgs instead of pngs for better quality?

**Comment by andrew032011** [comment]
Wow! That's a big diff. I think you picked up a few extra commits here. Can you try cherry picking your changes to a separate branch?

**Comment by andrew032011** [comment]
Closing this due to a bad rebase. @kevinmram landed this change in https://github.com/cornell-dti/idol/pull/538.

**Pull request closed without merging**
