### PR TITLE
Hide broken/in-progress pages from users.

### PR DESCRIPTION
**Pull request by JacksonStaniec**
### Summary 

This PR removes access to broken pages or features that are not ready for release.
- Removed "Games" tab
- Add message if user's arent supposed to see candidate decider instances
- Hide shoutouts feature until ready for use

### Test Plan 

Non-admin view
image

image

### CODE REVIEW

**Review by henry-li-06 — COMMENTED** [review]
Candidate decider _should not_ be hidden for non-admins. Members can only see the instances that they have access to which for most non-tpms and admins should be none.

**Comment by JacksonStaniec** [comment]
> Candidate decider _should not_ be hidden for non-admins. Members can only see the instances that they have access to which for most non-tpms and admins should be none.

Alright I didn't know non-admins would be using it at all. Do you think it would be a good idea to add some text saying something like "You don't have to access to any right now" if a member doesn't have access just so theres not a blank screen when they're looking on the page?

**Comment by henry-li-06** [comment]
> > Candidate decider _should not_ be hidden for non-admins. Members can only see the instances that they have access to which for most non-tpms and admins should be none.
> 
> Alright I didn't know non-admins would be using it at all. Do you think it would be a good idea to add some text saying something like "You don't have to access to any right now" if a member doesn't have access just so theres not a blank screen when they're looking on the page?

Well just for example most tpms aren't even admins and would need access to be able to review dev apps. But yeah I think that's probably a great idea.

**Comment by JacksonStaniec** [comment]
> > > Candidate decider _should not_ be hidden for non-admins. Members can only see the instances that they have access to which for most non-tpms and admins should be none.
> > 
> > 
> > Alright I didn't know non-admins would be using it at all. Do you think it would be a good idea to add some text saying something like "You don't have to access to any right now" if a member doesn't have access just so theres not a blank screen when they're looking on the page?
> 
> Well just for example most tpms aren't even admins and would need access to be able to review dev apps. But yeah I think that's probably a great idea.

Yea that makes sense. Let me know if you think the message is okay.

**Review by henry-li-06 — APPROVED** [review]
LGTM

**Pull request merged**
