### PR TITLE
Website Redesign: Spacing improvement

### PR DESCRIPTION
**Pull request by JasonMun7**
### Summary 

This pull request is the first step towards implementing feature Foo

- [x] implemented a new SectionWrapper Component to help with margins/spacing (note in the x direction)
- [x] Applied spacing to navbar, footer, hero Sections, and respective content

### Notion/Figma Link 

[Spacing Ticket](https://www.notion.so/New-Website-Use-same-margins-on-every-page-footer-navbar-14a0ad723ce18026a661c596bdec6724?pvs=4)

### Test Plan 

https://github.com/user-attachments/assets/c4a360ce-8eee-4c26-a9f7-750ff1deb50b
https://github.com/user-attachments/assets/114b57f1-a62e-47ec-8d3d-9d8b82dcf3ae

### Notes 

- In the future, I would like to Standardize and organize some of the components in order to use the Section Wrapper more effectively as I have to use it specific components rather than a layout for now 
- Definitely something we can do in the future

### CODE REVIEW

**Comment by andrew032011** [comment]
Thanks so much for this! Since this is a major refactor, could you resolve merge conflicts before we do a careful review through all the pages?

**Comment by andrew032011** [comment]
Screenshot 2024-12-06 at 10 55 03 PM
The left/right gaps here feels a little too much. @Bookie0 thoughts?

**Review by Bookie0 — COMMENTED** [review]
Seems like some of the margins are still a bit off/unequal?

i drew some lines to visualize it [here](https://www.figma.com/design/ttAGEX3pHmzuhMzp8uAyhz/DTI-New-Landing-Website?node-id=582-304&node-type=section&t=awZGFbRLuPiyewWY-11)

**Comment by Bookie0** [comment]
> The left/right gaps here feels a little too much. @Bookie0 thoughts?

eh i dont think its too bad..
we made it `1200px` max width. I dont think we want it any bigger or else the content becomes very wide (especially text) so its a bit harder to read. Am thinking especially the hero sections of all the pages (except home page) where the headers are quite long

**Review by Bookie0 — APPROVED** [review]
yay for alignment!

**Review by andrew032011 — APPROVED** [review]

**Pull request merged**
