### PR TITLE
Candidate Decider Styling

### PR DESCRIPTION
**Pull request by andrew032011**
### Summary 

-Add spacing to buttons/search bar
-style save button, change from Form button to just Ui Blue Button
-fix vertical alignment of "Candidate ID" and "of ##" text
-looking to add more color, **Suggestions would be appreciated!!**

This pull request is the first step towards adding styles/spacing/colors to candidate decider

- [x] implemented candidate decider styling

### Notes
-Goal is to add some more color too. Henry is going to look into coloring the rating buttons, but in general I couldn't find other places to add any more color. **Suggestions would be appreciated if you have any!!**
**Candidate decider (with comment field lengthened)**
Screen Shot 2022-04-10 at 4 06 17 PM
**Styled /candidate-decider page**
Screen Shot 2022-04-10 at 4 02 48 PM

**Video of loading screen:**

https://user-images.githubusercontent.com/59291082/161852607-a3d1456f-d349-441c-becc-9cc59be56410.mov

### CODE REVIEW

**Comment by henry-li-06** [comment]
Would you be able to add screenshots?

**Comment by andrew032011** [comment]
Screenshot attached.

**Review by henry-li-06 — COMMENTED** [review]
I think the search bar could be a little longer, otherwise looks pretty good!

**Comment by henry-li-06** [comment]
> I think the search bar could be a little longer, otherwise looks pretty good!

I think search bar can still be longer (as in much much longer) -- there should be enough space for someone to type a reasonable comment about some candidate

**Comment by henry-li-06** [comment]
Also the page `/candidate-decider` still needs styling. This page should have a dashboard of all the Candidate Decider  instances but the styling is very barebones (basically nonexistent).

**Comment by andrew032011** [comment]
> > I think the search bar could be a little longer, otherwise looks pretty good!
> 
> I think search bar can still be longer (as in much much longer) -- there should be enough space for someone to type a reasonable comment about some candidate

Would that mean extending all the way to the end of the page? That would involve moving the progress bar stuff down to make room right?

**Comment by henry-li-06** [comment]
> > > I think the search bar could be a little longer, otherwise looks pretty good!
> > 
> > 
> > I think search bar can still be longer (as in much much longer) -- there should be enough space for someone to type a reasonable comment about some candidate
> 
> Would that mean extending all the way to the end of the page? That would involve moving the progress bar stuff down to make room right?

not necessarily, 2-3x the current size would probably be fine

**Comment by andrew032011** [comment]
> > > > I think the search bar could be a little longer, otherwise looks pretty good!
> > > 
> > > 
> > > I think search bar can still be longer (as in much much longer) -- there should be enough space for someone to type a reasonable comment about some candidate
> > 
> > 
> > Would that mean extending all the way to the end of the page? That would involve moving the progress bar stuff down to make room right?
> 
> not necessarily, 2-3x the current size would probably be fine

Oh huh, are you talking about the comment text field? The search bar wouldn’t fit on the page if the length was doubled.

**Comment by henry-li-06** [comment]
> > > > > I think the search bar could be a little longer, otherwise looks pretty good!
> > > > 
> > > > 
> > > > I think search bar can still be longer (as in much much longer) -- there should be enough space for someone to type a reasonable comment about some candidate
> > > 
> > > 
> > > Would that mean extending all the way to the end of the page? That would involve moving the progress bar stuff down to make room right?
> > 
> > 
> > not necessarily, 2-3x the current size would probably be fine
> 
> Are you talking about the comment text field? The search bar wouldn’t fit on the page if the length was doubled. Or maybe if you could give me a quick sketch so I know generally what you mean?

Ohhh yes yes my bad

**Comment by andrew032011** [comment]
No worries! Just pushed a change to address the feedback you mentioned, for now just adding a margin for the dashboard, can't think of anything else at the moment. Also updated the screenshots.

**Review by henry-li-06 — APPROVED** [review]
Nice work, LGTM!
```
              |    |    |                 
             )_)  )_)  )_)              
            )___))___))___)\            
           )____)____)_____)\\
         _____|____|____|____\\\__
---------\                   /---------
  ^^^^^ ^^^^^^^^^^^^^^^^^^^^^
    ^^^^      ^^^^     ^^^    ^^
         ^^^^      ^^^
```

**Pull request merged**
