### PR TITLE
add name

### PR DESCRIPTION
**Pull request by andrew032011**
### Summary 

Add name to readme, create Fall 2022

### CODE REVIEW

**Comment by henry-li-06** [comment]
Can you just add everyone?

**Comment by andrew032011** [comment]
> 

Sure

**Comment by andrew032011** [comment]
Do we keep the tradition of leaving Devs' names only or should we add design + PM?

**Comment by henry-li-06** [comment]
> Do we keep the tradition of leaving Devs' names only or should we add design + PM?

It seems like other repos also include PM + design so we should probably do that as well

**Review by henry-li-06 — APPROVED** [review]

**Pull request merged**
