### PR TITLE
Adds documentation to TeamEventAttendanceDao.ts

### PR DESCRIPTION
**Pull request by alyssayzhang**
### Summary 

This PR finishes up documenting all the classes and functions in `TeamEventAttendanceDao.ts`

### CODE REVIEW

**Review by kevinmram — APPROVED** [review]
LGTM!

**Review by oscarwang20 — CHANGES_REQUESTED** [review]
I would advise against doing this just for the documentation requirement. The names are pretty self explanatory here.

**Review by andrew032011 — CHANGES_REQUESTED** [review]
I would have to agree with Oscar. Those are inherited functions so it's not telling too much than what BaseDao mentions. I think we could keep the docstring for the class, but also it does not add more info.

**Comment by andrew032011** [comment]
@alyssayzhang Doing some cleanup here. Are we good to close this PR for the time being? If we want to add documentation to this file later on that's fine too. Just don't want this PR to get stale.

**Comment by alyssayzhang** [comment]
> @alyssayzhang Doing some cleanup here. Are we good to close this PR for the time being? If we want to add documentation to this file later on that's fine too. Just don't want this PR to get stale.

Yeah I'll close it!

**Pull request closed without merging**
