### PR TITLE
Connect admin forms for team event credit to the api and display details

### PR DESCRIPTION
**Pull request by riyajaggi**
### Summary 

This pull request connects the admin forms for the team event credit to the api to create new events and display their details. The backend endpoints were updated to support the following.

- [x] create team event and update firebase
- [x] fetch and display all team events
- [x] fetch and display team event details
- [x] edit team events
- [x] delete team events

next pr:
- [ ] admin approval of members

### Test Plan 

tested the endpoints and above functionality locally; data collection was updated as expected and was displayed on frontend

**Creation of Team Event and Fetching all Team Events**
image

**Team Event Details**
image

### CODE REVIEW

**Comment by andrew032011** [comment]
In the event editor, changes in event properties don't show up until the page is refreshed.

**Review by andrew032011 — CHANGES_REQUESTED** [review]
[Deleted]

**Review by andrew032011 — COMMENTED** [review]
In the event editor, changes in event properties don't show up until the page is refreshed.

**Comment by riyajaggi** [comment]
@henry-li-06 @andrew032011 fixed! both pages should now display the updated team event(s) without manual refresh

**Review by andrew032011 — APPROVED** [review]

**Comment by andrew032011** [comment]
When we create team events and click the "Create Event" button, should we keep all the information populated in the fields? Or do you think it might be better to clear them so it's easier to make another event?

**Comment by airaagrawal1** [comment]
> When we create team events and click the "Create Event" button, should we keep all the information populated in the fields? Or do you think it might be better to clear them so it's easier to make another event? Right out when you create the event, all the info are still in the fields so you could keep clicking the "Create Event" button.

When I tested and created new events, I did not have this issue. After the confirmation that the event was created, the fields were cleared so I could type in new information.

**Comment by andrew032011** [comment]
> > When we create team events and click the "Create Event" button, should we keep all the information populated in the fields? Or do you think it might be better to clear them so it's easier to make another event? Right out when you create the event, all the info are still in the fields so you could keep clicking the "Create Event" button.
> 
> When I tested and created new events, I did not have this issue. After the confirmation that the event was created, the fields were cleared so I could type in new information.

I'm on https://deploy-preview-254--cornelldti-idol.netlify.app/admin/team-events, and this is what I saw. Are you also testing on that page?

https://user-images.githubusercontent.com/59291082/156934119-6afb85c9-f615-43ac-9b0a-7aa015bcbd7d.mov

**Comment by airaagrawal1** [comment]
> > > When we create team events and click the "Create Event" button, should we keep all the information populated in the fields? Or do you think it might be better to clear them so it's easier to make another event? Right out when you create the event, all the info are still in the fields so you could keep clicking the "Create Event" button.
> > 
> > 
> > When I tested and created new events, I did not have this issue. After the confirmation that the event was created, the fields were cleared so I could type in new information.
> 
> I'm on https://deploy-preview-254--cornelldti-idol.netlify.app/admin/team-events, and this is what I saw. Are you also testing on that page?
> 
>  Screen.Recording.2022-03-06.at.12.15.34.PM.mov

I tried it again and seems like you're right! Yup, we probably don't want this in case an admin accidentally makes the same event again.

**Comment by riyajaggi** [comment]
@andrew032011 @airaagrawal1 good catch! we actually keep the values in the other forms, but for this case I can see how that could lead to multiple same events or slow them down when creating multiple forms in a sitting.

I'll change this in a separate pr and merge this for now!

**Pull request merged**
