### PR TITLE
add name to contributors list

### PR DESCRIPTION
**Pull request by patriciaahuang**
### Summary 

This pull request is to update the contributors list in the README.

### CODE REVIEW

**Review by andrew032011 — APPROVED** [review]

**Review by alyssayzhang — COMMENTED** [review]
@andrew032011 Do we need these yarn.lock changes here? I think these changes should not be here but I also had this issue where a lot of changes were initially added to my README PR after setting up my dev env.

**Comment by andrew032011** [comment]
> do we need these yarn.lock changes here?

Good point @alyssayzhang. Thank you! @patriciaahuang could you revert the changes that are not in the README please?

**Review by andrew032011 — CHANGES_REQUESTED** [review]
> do we need these yarn.lock changes here?

Good point @alyssayzhang. Thank you! @patriciaahuang could you revert the changes that are not in the README please?

**Comment by andrew032011** [comment]
I'm actually very curious when/how they show up. I wonder if it's when you run `yarn` for the first time and it does that. I've never run into it, but I also haven't had to run `yarn add`/ `yarn install`/`yarn` in awhile.

**Review by andrew032011 — APPROVED** [review]

**Comment by andrew032011** [comment]
This branch picked up some more changes that shouldn't be here. I talked to @kevinmram and he's going to add the names separately.

**Pull request closed without merging**
