### PR TITLE
Website: More Team Page Improvements

### PR DESCRIPTION
**Pull request by cchrischen**
### Summary 
This PR contains even more team page fixes from the latest leads sync.
- [ ] Update image and quality
- [x] Standardize card and member details border radius
- [x] Wrap subteam section of member details in `<a>` tag
- [x] Add hover states to connect icons; change opacity to 0.6 on focus
- [x] Fix issue with long names on small viewports

### Notion/Figma Link 
[Notion](https://www.notion.so/Idol-Lead-Sync-781de97ad403492b94b420349f829ea5)

### Test Plan 
Netlify deploy vs. current website.

### Notes 
I cannot figure out how to avoid the weird shifting ... if anyone could help :)

### CODE REVIEW

**Comment by andrew032011** [comment]
Looks good so far!

**Review by Bookie0 — CHANGES_REQUESTED** [review]
nice on the changes!

just a weird thing i found while testing – it seems like the opening/closing of cards has regressed:

- despite there being a `cursor: pointer;`, clicking the image doesn't open the profile
- the page layout shifts when you open the card







[see video uploaded on slack ](https://cornelldti.slack.com/archives/C01BYPLV0KY/p1734577576xxxx31)

**Comment by Bookie0** [comment]
while we're at it, let's also make the expanded card the same width as the row of cards:
Screenshot 2024-12-18 at 10 07 39 PM

**Comment by JasonMun7** [comment]
Hey Chris! This is looking great so far! I was just wondering how you were going about standardizing your fonts? Are you adding them to the tailwind css or just using the standard utility? Wanted to make sure that I was consistent with what you're doing as well!

**Review by Bookie0 — CHANGES_REQUESTED** [review]
i saw andrew re-requested my review but im not sure the expanded card profile opening bug has been fixed? I still cannot seem to open the profile consistently.

see [this](https://github.com/cornell-dti/idol/pull/801#pullrequestreview-2513223574) (and [this](https://github.com/cornell-dti/idol/pull/801#issuecomment-2552680747))

**Comment by andrew032011** [comment]
Oh sorry I didn't double check. I just saw commits were made so I figured it was ready for review again. I'll let @cchrischen request you when it's actually ready.

**Review by Bookie0 — APPROVED** [review]
works for me now yay!

**Review by andrew032011 — APPROVED** [review]

**Review by JasonMun7 — APPROVED** [review]
Awesome Job! I'll just wait till this merges to standardize the fonts!

**Pull request merged**
